name: Deploy

on:
  workflow_dispatch:
  push:
    branches: [main]

env:
  KAMAL_DOMAIN_NAME: ${{ secrets.KAMAL_DOMAIN_NAME }}
  KAMAL_WEB_SERVER_IP: ${{ secrets.KAMAL_WEB_SERVER_IP }}
  KAMAL_SSH_USER: ${{ secrets.KAMAL_SSH_USER }}
  RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
  KAMAL_SSH_PRIVATE_KEY: ${{ secrets.KAMAL_SSH_PRIVATE_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Install dependencies
        run: gem install kamal

      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ env.KAMAL_SSH_PRIVATE_KEY }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Run deploy command
        run: kamal deploy
